[project]
name = "agent-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "deepagents>=0.5.1",
  "fastmcp>=3.2.4",
  "langchain>=1.2.15",
  "langchain-daytona>=0.0.7",
  "langchain-deepseek>=1.0.1",
  "langchain-huggingface>=1.2.2",
  "langchain-mcp-adapters>=0.2.2",
  "langchain-milvus>=0.4.0",
  "langchain-openai>=1.1.12",
  "langchain-quickjs>=0.1.2",
  "langchain-tavily>=0.2.17",
  "langchain-text-splitters>=1.1.2",
  "langchain-unstructured>=1.0.1",
  "langgraph>=1.1.6",
  "llama-index>=0.14.23",
  "llama-index-embeddings-huggingface>=0.7.0",
  "llama-index-llms-openai-like>=0.7.2",
  "notebook>=7.5.5",
  "openai>=2.41.0",
  "requests>=2.34.2",
  "sentence-transformers>=5.6.1",
  "tavily-python>=0.7.24",
  "unstructured[md,pdf]>=0.24.1",
]
